version: "3"

services:
  app:
    build: .
    command: sleep infinity
    init: true
    ports:
      - 3000:3000
    volumes:
      - .:/app

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
